Caching
semaphoreci/docs pull request #1127
Opened 2022-02-14 13:46 UTC by JNunez1204

This look ok so far?

2022-02-17 10:06 UTC, csidyel requested changes

2022-02-18 13:06 UTC, JNunez1204 commented on docs/essentials/caching-dependencies-and-directories.md
> +This is the default backend for jobs running in Semaphore's hosted environment The
Yes, there is, apologies

2022-02-22 16:11 UTC, JNunez1204 commented on docs/essentials/caching-dependencies-and-directories.md
> +(exit with 0 status).
the explanation of what it is was the reason i changed it; perhaps it should be exit with a value or something but as a lamen this didn't make sense and it's hard when i don't know exactly what 'non-zero status' means

2022-02-22 16:11 UTC, JNunez1204 commented on docs/essentials/caching-dependencies-and-directories.md
> +### `cache restore` will restore an archive with a corrupted archive message
changed, but recommend removing the header formatting and putting a period at the end

2022-02-23 07:01 UTC, csidyel approved these changes

2022-02-23 07:01 UTC, merged