Artifacts: Update of the Essentils document + Introduction of Retention Policies
semaphoreci/docs pull request #1134
Opened 2022-02-18 11:38 UTC by shiroyasha

In this PR, I am:

- Touching up the content of the artifacts. The new essentials page is now focused on "why you need artifacts, and what can you do with them".
- Adding screenshots to the artifacts page. App screenshots boost the "understandability" of the content.
- Introducing retention policies for controlling the lifetime of artifacts
- Introducing retention policies reference

---

Artifact retention policies are a new concept in Semaphore 2.0. They are not yet released as a feature. A presentation of this feature is due to the internal team before the feature is released.

For some of you in the review list, retention policies are a new concept. Your feedback is the most useful, as you have the unique opportunity to judge if the concept is understandable just based on the docs.

2022-02-18 14:42 UTC, mateuscap commented on docs/essentials/artifacts.md
> +We can set up a retention policy that matches that matches our previous needs. One
```suggestion
We can set up a retention policy that matches our previous needs. One
```

2022-02-18 14:42 UTC, mateuscap commented on docs/essentials/artifacts.md
> +week for screenshots, and 3 months for test logs. We will also set one months for
```suggestion
week for screenshots, and 3 months for test logs. We will also set one month for
```

2022-02-18 15:02 UTC, mateuscap reviewed
_Your feedback is the most useful, as you have the unique opportunity to judge if concept is understandable just based on the docs._

The concept is understandable to me

2022-02-21 14:01 UTC, csidyel requested changes
I'll ask Christopher to review this page after the merge.

2022-02-23 10:54 UTC, merged