Update the Getting Started guide
semaphoreci/docs pull request #1208
Opened 2022-07-05 09:40 UTC by obedrina

Added the information about Bitbucket
@AleksandarCole could you please review when you have a chance? Thank you!

2022-07-11 16:22 UTC, markoa requested changes
Overall good changes, it's some formatting that needs a revision. I took a look since it's been a while since you submitted and I created the original page.

2022-07-11 16:22 UTC, markoa commented on docs/guided-tour/getting-started.md
> +- Create a new repository on [Github][github-new] or [Bitbucket](https://bitbucket.org/new/)
follow the pattern of formatting links that's used throughout the page, where the name/URL pairs are defined at the bottom

2022-07-11 16:22 UTC, markoa commented on docs/guided-tour/getting-started.md
> +❗Info: "Running parallel jobs simultaneously is possible under open source, free trial, or paid [plans][plans]."
are you sure about this formatting change? it's special markup for an info box, it's not supposed to be an exclamation mark

2022-07-14 09:26 UTC, obedrina reviewed
Fixed the formatting as per the comments from Marko

2022-07-14 09:27 UTC, obedrina commented
@markoa I updated the file as per the comments. Could you please take another look?
Thank you!

2022-07-21 15:11 UTC, markoa approved these changes
Good to go!

2022-07-21 15:12 UTC, merged