Adding new machines specs
semaphoreci/docs pull request #1291
Opened 2022-12-28 13:11 UTC by AleksandarCole

2022-12-28 13:18 UTC, bogyo210 requested changes

2022-12-28 13:18 UTC, bogyo210 commented on docs/ci-cd-environment/machine-types.md
> +3. `Disk` is implemented as RAM drive backed by DDR4 RAM.
Disks are backed by NvME drives.

2022-12-28 13:18 UTC, bogyo210 commented on docs/ci-cd-environment/machine-types.md
> +3. `Disk` is implemented as RAM drive backed by DDR4 RAM.
Disks are backed by NvME drives

2022-12-28 13:29 UTC, csidyel commented on docs/ci-cd-environment/machine-types.md
> +The `e1` series machines are our first generation, cost-effective with medium performance they are a good choice for less compute and memory intensive jobs.
I'd split the sentence into two to keep them shorter.

The `e1` series machines are our first generation, cost-effective with medium performance. They are a good choice for less compute and memory-intensive jobs.

2022-12-28 13:34 UTC, csidyel commented on docs/ci-cd-environment/machine-types.md
> +The `f1` series machines are built for compute-intensive jobs, these machines deliver highest performance..
deliver the highest performance.

there are two dots at the end of `performance..`

2022-12-28 13:36 UTC, csidyel requested changes
my notes

2023-01-06 09:43 UTC, AleksandarCole commented
Closed in favor of: https://github.com/semaphoreci/docs/pull/1292
All suggestions and requested changes are implemented in that PR. Thanks @bogyo210 and @csidyel!

2023-01-06 09:43 UTC, closed without merging