Parameterized promotions
semaphoreci/docs pull request #1292
Opened 2022-12-28 21:26 UTC by AleksandarCole

2022-12-29 08:13 UTC, csidyel requested changes

2022-12-29 08:13 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +- In the UI form if promotion is triggered manually
if the promotion

2022-12-29 08:13 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +- Through the API call
Through -> Via

2022-12-29 08:13 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +- Through `default_value` in combination with `auto_promote`
Through -> Via

2022-12-29 08:13 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +pipelines. You can do this either through a form in the UI,
via a form

2022-12-29 08:13 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +In the Semaphore web interface, you will see a deployment button.
You will see a deployment button in the Semaphore web interface.

2022-12-29 08:13 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +When clicked, a UI form will be auto-generated based on the configuration in the initial pipeline, prompting you for parameter values before starting the promotion.
of the initial pipeline. This will prompt you for parameter values before starting the promotion.

2022-12-29 08:13 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +Here's what it looks like for the `.yml` code from our example:
what -> how

2022-12-29 08:13 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +### Setting the values through the API
through -> via

2022-12-29 08:13 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +Parameters can also be passed to the promotion pipeline when the promotions are triggered through Semaphore API.
You can also pass parameters to the promotion pipeline when promotions are triggered via the Semaphore API.

2022-12-29 18:14 UTC, DamjanBecirovic commented on docs/essentials/parameterized-promotions.md
> +          default_value: $SEMAPHORE_GIT_PR_NAME
This will not work, the value will be the actual string `"$SEMAPHORE_GIT_PR_NAME"` and not the value of the environment variable with that same name.

2023-01-06 09:41 UTC, AleksandarCole commented on docs/ci-cd-environment/machine-types.md
> +`e2` machines are currently only available on our [enterprise plan](https://semaphoreci.com/pricing).
Good point, I've removed this reference altogether as it will not be relevant soon.

2023-01-06 10:45 UTC, bogyo210 commented on docs/ci-cd-environment/machine-types.md
> +3. `Disk` is implemented as RAM drive backed by DDR4 RAM.
Backed by NvME drives.

2023-01-06 10:47 UTC, bogyo210 approved these changes
I reviewed the machine/agent part, seems ok

2023-01-06 11:35 UTC, DamjanBecirovic approved these changes

2023-01-06 11:35 UTC, csidyel requested changes

2023-01-06 11:35 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +Let's start with defining the parameters that our promotion will support.
`with` -> `by`

2023-01-06 11:35 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +- **default_value** - Can only be set if the parameter is required, it
Can only be set if the parameter is required. It is a default value of the parameter.

2023-01-06 11:35 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +- **options** - Use this to define a list of all possible values and the user will have to select one of them from the dropdown menu. If omitted, the user will be able to input any value via the inpu
Use this to define a list of all possible values. The user needs to select a value from the dropdown menu. If omitted, the user is able to input any value via the input box.

changed to present tense and used shorter sentences.

2023-01-06 11:35 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +- **description** - This is a description text that gets rendered on
(when a user selects values) -> (when a user selects values).

dot at the end

2023-01-06 11:35 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +Now that we have defined our parameters, it is time to define how they are used in the promoted pipeline.
it is time to define how to use them in the promoted pipeline. 

passive to active voice.

2023-01-06 11:35 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +Promotion parameters can be used in the following way:
You can use promotion parameters in the following way:

passive to active voice.

2023-01-06 11:35 UTC, csidyel commented on docs/essentials/parameterized-promotions.md
> +**Note:** For this example pipeline to work, secrets named `creds-for-Production` and `creds-for-Stage` have to exist in the organization.
secrets -> the secrets

have to exist -> must exist

2023-02-15 13:09 UTC, merged