Updating "sem get secret" instances
semaphoreci/docs pull request #1452
Opened 2024-07-04 10:18 UTC by tbogosavljevic

Because we changed the way our API works, the "sem get secret" does not provide the contents of the secret anymore. I have updated the documentation to reflect that.

2024-07-04 12:47 UTC, hamir-suspect requested changes

2024-07-04 13:00 UTC, tbogosavljevic commented on docs/reference/sem-command-line-tool.md
> +Similarly, in order to find out the list of secrets in a `secret`, named `mySecrets`,
You're right, that sounds better. Changed it, thank you!

2024-07-04 19:51 UTC, mateuscap approved these changes

2024-07-05 13:32 UTC, hamir-suspect approved these changes

2024-07-05 13:53 UTC, ivanaur approved these changes

2024-07-08 10:35 UTC, merged