PHP switching method clarification
semaphoreci/docs pull request #953
Opened 2021-02-09 14:44 UTC by dradulescu

Someone was recently confused about the example, it gives the impression that both commands have to be used. It should be either `sem-version` or `phpbrew`.

2021-02-09 14:47 UTC, bogyo210 requested changes
They are not the same: sem-version downloads a precompiled binary while phpbrew downloads and compiles a fresh instance

2021-02-10 09:37 UTC, dradulescu commented
I understand. So `sem-version` should be faster while `phpbrew` can be used to grab versions not already present, right?
Aren't the commands in the example redundant in this case?

2021-02-10 10:08 UTC, bogyo210 commented
No. Sem-version downloads a precompiled php from our servers, activates it and done. ~10s
Phpbrew downloads the php sources and builds them. ~ 7 minutes

Sem-version uses phpbrew to activate an existing php version on the servers.

2021-05-18 17:18 UTC, dradulescu commented
@bogyo210 sorry for the late ping here, but I've added the changes as we discussed. Please let me know if this is clear enough 🙇🏻

2021-05-18 18:38 UTC, bogyo210 approved these changes

2021-05-18 19:07 UTC, merged